### ISSUE TITLE
Don't remove old tags

### ISSUE THREAD

**Issue by cassidyjames** [rajkumaar23/badgie#17]
Unless I'm missing something, it looks like you've removed previous releases/tags for Badgie. This makes it really hard to review your app submissions for AppCenter, as we must review the code from scratch instead of comparing it to your previous release. In the future, we recommend using GitHub Releases and not modifying previous releases.

**Comment by rajkumaar23** [comment]
Sure. Sorry for that! @cassidyjames

**Comment by cassidyjames** [comment]
No worries! Just wanted to point it out. 😁
