### ISSUE TITLE
Change required for AppCenter: Release description

### ISSUE THREAD

**Issue by cassidyjames** [rajkumaar23/badgie#18]
Thanks for submitting your 0.2.0 update to AppCenter! However, while reviewing the submission, we found an issue that needs to be resolved.

Updates must include accurate [release descriptions](https://docs.elementary.io/develop/appcenter/publishing-updates#release-descriptions). Please detail the user-facing changes in the proper tag.

Once you've made the requested changes, create a new release on GitHub and re-submit it to the [AppCenter Dashboard](https://developer.elementary.io). You can include the 0.2.0 details in the next version's release description (e.g. 0.2.1) since 0.2.0 will have never reached users.

As always, if you have any questions you can reply here.

**Comment by rajkumaar23** [comment]
@cassidyjames Thanks! I have updated the description and submitted the new release to AppCenter.

**Comment by cassidyjames** [comment]
Resolved in 0.2.1
