### ISSUE TITLE
New logo suggestion

### ISSUE THREAD

**Issue by darltrash** [rajkumaar23/badgie#26]
I think the current logo doesnt really fits within the elementaryOS style, so I made my own version of the logo for Badgie following the [official elementaryOS HIG](https://elementary.io/es/docs/human-interface-guidelines#iconography). 

This is just a suggestion, But i think it would be awesome to have a consistent style within all elementaryOS apps :)

![path866](https://user-images.githubusercontent.com/38925212/102288160-a54e3e00-3f1a-11eb-849c-6fc9f7875813.png)
[badgielogo.zip](https://github.com/rajkumaar23/badgie/files/5699442/badgielogo.zip) (svg file)

**Comment by darltrash** [comment]
I forgot to add that this depends on the "Raleway" font which comes installed within every eOS install (afaik)

**Comment by rajkumaar23** [comment]
@darltrash Thanks for the suggestion! However, I'm not planning to change the logo of the app anytime soon. Hence, I'm closing this issue. Will reopen if I plan to change it anytime in the future. 

Thanks again! :)
