### ISSUE TITLE
Update flatpak platform to version 6

### ISSUE THREAD

**Issue by danirabbit** [rajkumaar23/badgie#30]
Hey there!

I'm working right now on manually uploading apps while we're finishing up the new dashboard. It looks like your app is ready to go, except that it's still using the daily version of the flatpak platform instead of the stable version 6. As soon as that is updated and you make a release, I would love to get Badgie published :)

**Comment by rajkumaar23** [comment]
Fixed in https://github.com/rajkumaar23/badgie/commit/e74e1c942eb8766c5b36e7428c5c8bd7f6aaca77
