### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by danirabbit** [rajkumaar23/badgie#31]
I left you a comment on https://github.com/elementary/appcenter-reviews/pull/45 but you probably didn't see it!

It looks like your screenshot needs to be updated for elementary OS 6 and then I think you're good to go for releasing Badge into AppCenter as Flatpak :)

**Comment by rajkumaar23** [comment]
Will do that, @danrabbit 👍🏼

**Comment by rajkumaar23** [comment]
Can you please let me know which tool do you use to capture screenshots with a shadow in the background, as well as including the close button like [this one](https://raw.githubusercontent.com/danrabbit/lookbook/main/data/screenshot.png)? 

I tried using the default screenshot tool and this is what I got while capturing the current window.


![](https://raw.githubusercontent.com/rajkumaar23/badgie/master/data/screenshots/1.png)

**Comment by danirabbit** [comment]
Ah, It looks like because your app doesn't define its own headerbar that it's using the default server-side decorations and we're not capturing those. I've filed an issue about this here: https://github.com/elementary/gala/issues/1191

You can workaround this by running your app from terminal with `GTK_CSD=1` as in:

```
GTK_CSD=1 ./com.github.rajkumaar23.badgie
```
