### ISSUE TITLE
Change required for AppCenter: OARS Social Info inaccurate

### ISSUE THREAD

**Issue by cassidyjames** [rajkumaar23/badgie#4]
Thanks for submitting your app to AppCenter! While reviewing your app, we noticed it hits an external API but has its `social-info` OARS data set to `none`:

https://github.com/rajkumaar23/badgie/blob/0310ec0268b288179e3ff4c012ab5a48aed7b783/data/com.github.rajkumaar23.badgie.appdata.xml#L39

This must be set to `mild` or higher depending on the type of data sent. If no data is sent, it must be `mild` since it is hitting an external API and could be leaking IP address information.

We recommend using the official OARS Generator to ensure your app's rating information is accurate and will pass our review: https://hughsie.github.io/oars/generate.html

Please correct this before submitting a new release to AppCenter for review.

If you have any questions, feel free to ask!

**Comment by rajkumaar23** [comment]
Sure, the only data sent is the Android App's package name. The API's source code is https://github.com/rajkumaar23/playstore-api

So what should I set the value to ?

**Comment by cassidyjames** [comment]
@rajkumaar23 the OARS Generator lists these examples:

- Mild: Using any online API, e.g. a user-counter
- Moderate: Sharing diagnostic data not identifiable to the user, e.g. profiling data
- Intense: Sharing information identifiable to the user, e.g. crash dumps

So for your app, `mild` seems appropriate.

**Comment by rajkumaar23** [comment]
Okay, thanks. Will update and create a release.

**Comment by rajkumaar23** [comment]
@cassidyjames I have updated and submitted the new release for review. Please look into it.
