### ISSUE TITLE
Change required for AppCenter: Install icons

### ISSUE THREAD

**Issue by cassidyjames** [rajkumaar23/badgie#5]
It looks like your build system isn't installing icons. You need to ensure the icons are installed for each of the required sizes, and for HiDPI (2× scaling) as well as loDPI.

If you provided your icons as SVG, you could add something like this to your top-level `meson.build`:

```meson
#Install our icons to the system
icon_sizes = ['32', '48', '64', '128']
foreach i : icon_sizes
    install_data(
        join_paths('data', 'icons', i + '.svg'),
        install_dir: join_paths(get_option('datadir'), 'icons', 'hicolor', i + 'x' + i, 'apps'),
        rename: meson.project_name() + '.svg'
    )
    install_data(
        join_paths('data', 'icons', i + '.svg'),
        install_dir: join_paths(get_option('datadir'), 'icons', 'hicolor', i + 'x' + i + '@2', 'apps'),
        rename: meson.project_name() + '.svg'
    )
endforeach
```

You may want to review the [icon guidelines](https://elementary.io/docs/human-interface-guidelines#iconography)—especially regarding pixel-fitting—to ensure your app icons look as good as they can in AppCenter and on elementary OS. You can also look at @micahilbery's [icon template project](https://github.com/micahilbery/elementary-icon-templates) for inspiration or a better starting point.

**Comment by rajkumaar23** [comment]
Okay, sure. Thanks. Is there a way I can verify that the app would pass the review before actually submitting ?

**Comment by rajkumaar23** [comment]
@cassidyjames I have added the script to install icons in my meson.build and published a new release.

**Comment by rajkumaar23** [comment]
@cassidyjames Since I'm a newbie to this, could you please check and let me know if I've to make any other changes?

**Comment by cassidyjames** [comment]
@rajkumaar23 looks like it's good now, your latest release was approved.
